name: 'my first container action'
description: 'test container'
author: 'drolsec'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'Tecknik Das Begeistert'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
